- hosts: node1
  tasks:
  - name: war deployment
    copy:
      src: "{{item}}"
      dest: /jboss/standalone/deployments/
     with_items:
       - jboss-helloworld.war
       - ticket-monster.war
     notify: restart_jboss
  handlers:
  - name: restart_jboss
    service:
      name: jboss
      state: restarted
